// bingwa-pro-backend/src/hybrid-connect/hybrid-connect.gateway.ts
// W5.F — HybridConnect socket relay. The phone (clientType 'phone') and the web portal
// (clientType 'portal') connect with the same Connect ID and join its room. The gateway is a
// dumb bridge: anything the phone emits is forwarded to that room's portals, and anything a
// portal emits is forwarded to the phone — so the event protocol (app_state.set, app.status,
// kpis.sync, transactions.sync, transaction.retry/delete, offers.sync, offer.update/delete,
// airtime_balance/used.sync) lives on the clients, exactly as in Hybrid (the server only routes).
import {
  OnGatewayConnection,
  OnGatewayDisconnect,
  WebSocketGateway,
} from '@nestjs/websockets';
import { Logger } from '@nestjs/common';
import { Socket } from 'socket.io';
import { HybridConnectService } from './hybrid-connect.service';

interface Room {
  phone?: Socket;
  portals: Set<Socket>;
}

@WebSocketGateway({ cors: { origin: '*' } })
export class HybridConnectGateway
  implements OnGatewayConnection, OnGatewayDisconnect
{
  private readonly logger = new Logger(HybridConnectGateway.name);
  private readonly rooms = new Map<string, Room>();

  constructor(private readonly service: HybridConnectService) {}

  handleConnection(client: Socket): void {
    const connectId = this.param(client, 'connectId');
    const clientType = this.param(client, 'clientType');
    // Only allow Connect IDs that were actually generated by an agent.
    if (!connectId || !this.service.agentFor(connectId)) {
      this.logger.warn(`Rejected socket: unknown connectId '${connectId}'`);
      client.disconnect(true);
      return;
    }
    const room = this.rooms.get(connectId) ?? { portals: new Set<Socket>() };
    if (clientType === 'phone') {
      room.phone = client;
    } else {
      room.portals.add(client);
    }
    this.rooms.set(connectId, room);
    client.data.connectId = connectId;
    client.data.clientType = clientType === 'phone' ? 'phone' : 'portal';
    this.logger.log(
      `Connected ${client.data.clientType} to room ${connectId} (portals=${room.portals.size}, phone=${!!room.phone})`,
    );
    this.broadcastPresence(connectId);
    // Generic relay — route every event to the other side of the room.
    client.onAny((event: string, ...args: unknown[]) =>
      this.relay(client, event, ...args),
    );
  }

  handleDisconnect(client: Socket): void {
    const connectId = client.data?.connectId as string | undefined;
    const clientType = client.data?.clientType as string | undefined;
    if (!connectId) return;
    const room = this.rooms.get(connectId);
    if (!room) return;
    if (clientType === 'phone' && room.phone === client) {
      room.phone = undefined;
    } else {
      room.portals.delete(client);
    }
    if (!room.phone && room.portals.size === 0) {
      this.rooms.delete(connectId);
    } else {
      this.broadcastPresence(connectId);
    }
  }

  private relay(from: Socket, event: string, ...args: unknown[]): void {
    const connectId = from.data?.connectId as string | undefined;
    const clientType = from.data?.clientType as string | undefined;
    if (!connectId) return;
    const room = this.rooms.get(connectId);
    if (!room) return;
    if (clientType === 'phone') {
      for (const portal of room.portals) portal.emit(event, ...args);
    } else {
      room.phone?.emit(event, ...args);
    }
  }

  /** Tell each side who's online so the portal can show Connected/Disconnected. */
  private broadcastPresence(connectId: string): void {
    const room = this.rooms.get(connectId);
    if (!room) return;
    const phoneOnline = !!room.phone;
    for (const portal of room.portals) {
      portal.emit('app.presence', { phoneOnline });
    }
    room.phone?.emit('app.presence', { portals: room.portals.size });
  }

  private param(client: Socket, key: string): string | undefined {
    const auth = client.handshake.auth as Record<string, unknown> | undefined;
    const query = client.handshake.query as
      | Record<string, unknown>
      | undefined;
    const v = auth?.[key] ?? query?.[key];
    return typeof v === 'string' ? v : undefined;
  }
}
